### ISSUE TITLE
[Question] How to combine quartz shard dust with flint dust in Steam Age?

### ISSUE THREAD

**Issue by chemlzh** [TerraFirmaGreg-Team/Modpack-1.20.x#214]
### Your Question

The quest book shows that by combining quartz shard dust with tiny flint dust, one can obtain glass dust. But I used REI to search the recipe, and found that there's no recipe suitable for steam age, since mixer needs electricity. So how can I combine these two dust in steam age? Could anyone help me?

**Comment by Wyrmlet** [comment]
According to modpack devs, you can use TFC's glassblowing mechanics to cast a block of glass into a basin of kaolin clay blocks (there should be something about that online), and then collect it with a gem saw. Then, use a macerator to grind up the glass into dust, which can be used for making vacuum tubes.
Also, make sure to get a mixer as your first machine! The quests are still not finished, so that isn't mentioned, but you can make most of the alloys needed for red and blue steel in the mixer, which will save you both time and 2 normal steel per ingot of each.

**Comment by chemlzh** [comment]
And here's another question: do kapok trees only produce latex in spring and summer? I have found that there is no latex dripping down to the wood bucket from taps on the kapoks.

**Comment by SpeeeDCraft** [comment]
Quests still not finished.
